### ISSUE TITLE
Place objects bug

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_policejob#54] opened 2018-03-19 07:51 UTC
I can't place objects after the last update. Cones, spikestrips etc.

**Comment by JaroSound** [comment] 2018-03-19 16:05
https://github.com/ESX-Org/esx_policejob/issues/53

**Comment by zarx1337** [comment] 2018-03-20 09:01
Does anybody know how to fix this bug?

**Comment by ElPumpo** [comment] 2018-04-05 09:41
... yet another duplicate of #58

**Closed by ElPumpo** 2018-04-05 09:41 UTC
Labels: bug, duplicate
