### ISSUE TITLE
I have found the bug for esx_policejob when placing objects!

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_policejob#57] opened 2018-03-28 00:22 UTC
The bug has to do with es_extended and esx_menu_default. I downgraded to an older version of es_extended and using the latest esx_policejob. Everything works fine!

**Comment by ElPumpo** [comment] 2018-04-05 09:36
Duplicate of #58, closing.

**Closed by ElPumpo** 2018-04-05 09:36 UTC
Labels: bug, duplicate

**Comment by zarx1337** [comment] 2018-04-05 12:00
Why do you close mine I was the one who found the bug? Close #58 instead..

**Comment by ElPumpo** [comment] 2018-04-09 08:50
Yep I should but the other one has more activity
