### ISSUE TITLE
Please tell me if it's a bug with placing objects?

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_policejob#56] opened 2018-03-27 16:57 UTC
I am hosting my server on zaphost. I don't know if it's possible it could be a database problem but I downloaded the server and tried to host it from my computer and spawn objects worked just fine!

**Comment by ElPumpo** [comment] 2018-04-05 09:39
Duplicate of #58

**Closed by ElPumpo** 2018-04-05 09:39 UTC
Labels: bug, duplicate
