### ISSUE TITLE
CheckID .. need some rework

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_policejob#115] opened 2018-06-26 22:18 UTC
If the player doesn't have his license permit the CheckID will never work, but once they have the "StreetCode" in their inventory, everything is working fine.

**Comment by nykroza** [comment] 2018-06-29 03:52
There is no error and I dunno how to do stack trace but to replicate you need 2 players or more.

player #1 is a cop that try to check the paper of player #2 
Since player #2 didn't do his license school he doesn't have the Streetcode from the dmvschool so player #1 can't check his paper, nothing will show up on player #1 side.

**Comment by ElPumpo** [comment] 2018-06-29 03:54
Your config?

**Comment by nykroza** [comment] 2018-06-29 19:14
https://pastebin.com/nGxF5BBE

Also there is another bug, if you handcuff someone, they are still able to shot with their firearm, it doesn't remove it from their hand

**Comment by ElPumpo** [comment] 2018-07-12 22:22
that bug has been fixed, can you still reproduce this issue?

**Comment by nykroza** [comment] 2018-07-16 21:42
Which one ?
For the cuff I fixed it on my side like 10 days ago
but for the CheckID I still have the problem, havn't tested your new script

**Comment by ElPumpo** [comment] 2018-07-28 10:35
I don't get it how people always find a way to break stuff. It works just fine for me and I haven't encountered any issues with it. Unless you provide some sort of stack trace then frankly I can't help. Try adding your own debug points or whatever.

**Comment by ElPumpo** [comment] 2018-07-28 10:38
Sounds like a duplicate of #66

**Closed by ElPumpo** 2018-07-28 10:38 UTC
Labels: bug, question
