### ISSUE TITLE
Blips

### ISSUE THREAD

**Issue by Ultrunz** [ESX-Org/esx_policejob#172] opened 2018-08-13 12:12 UTC
Config.EnableJobBlip              = true -- enable blips for colleagues, requires esx_society

does nothing, I have society setup, just wondering if there was an issue with this?

**Comment by ElPumpo** [comment] 2018-08-24 08:56
There's a known issue with it sometimes not adding the blips.

**Comment by ElPumpo** [comment] 2018-08-24 08:57
Duplicate of #125

**Closed by ElPumpo** 2018-08-24 08:57 UTC
Labels: bug, duplicate
