### ISSUE TITLE
CANT SEE PD BLIPS

### ISSUE THREAD

**Issue by stephen9898** [ESX-Org/esx_policejob#260] opened 2019-03-09 18:12 UTC
hi i enable blips for colleges but when in server it dost show them on the map can you please help me fix this updated all resources

**Comment by RedAlex** [comment] 2019-03-14 16:56
Same for us
We have update all to today and same problem with all original ressource.
Blips will show 0.1 second 
I continu to investigate.

**Comment by stephen9898** [comment] 2019-03-14 17:19
they wont show at all for us

**Comment by RedAlex** [comment] 2019-03-14 18:40
Test done :
Rollback server version to 1034 : Blips Not Work
Rollback essentialsmode to 5.0.2 : Blips Not Work
Rollback esx_policejob to 2 years ago : Blips Not Work
Erase fivem client cache : Blips Not Work
I continu to investigate.

**Comment by RedAlex** [comment] 2019-03-14 18:45
Found code in another ressource to remove player blips on map.
Fix for us.

**Comment by stephen9898** [comment] 2019-03-18 16:48
can you share please

**Comment by ElPumpo** [comment] 2019-04-22 07:53
Dupe of #125

**Closed** 2019-04-22 07:53 UTC
