### ISSUE TITLE
spawning objects doesn't work properly.

### ISSUE THREAD

**Issue by abbelol123** [ESX-Org/esx_policejob#58] opened 2018-03-29 20:41 UTC
In the esx_policejob object spawner, it sometimes spawns for me and sometimes don't.

**Comment by zarx1337** [comment] 2018-03-29 22:12
Indeed!

**Comment by ElPumpo** [comment] 2018-04-05 09:37
> The bug has to do with es_extended and esx_menu_default. I downgraded to an older version of es_extended and using the latest esx_policejob. Everything works fine!
Can someone verify this?

**Comment by HumanTree92** [comment] 2018-04-05 10:45
I'm using the latest of everything. The only thing that doesn't spawn for me is the Cones

**Comment by JaroSound** [comment] 2018-04-07 00:33
resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937' <--- Workin.
--resource_manifest_version '05cfa83c-a124-4cfa-a768-c24a5811d8f9' <--- Not Workin.

I think its the problem. After set the workin one in es_extended it works fine.

**Comment by sirmarknlddr** [comment] 2018-04-09 08:40
I can verify that the resource manifest is the issue. But changing that back will cause issues with els-plus or other scripts that use network ID's to function properly.

**Comment by benzon** [comment] 2018-04-10 23:35
Has any one tryed out changing manifest of esx_policejob to the newer version ?

But it is an issue that it dos not work, actually forces us to go back to the older esx_extended i think

**Comment by ElPumpo** [comment] 2018-04-15 07:39
Strange, I'm on the latest on everything and am not suffering from this issue. I honestly have no clue on what's going on

**Comment by Parme89** [comment] 2018-04-16 13:46
also having this issue , cant spawn anything :/

**Comment by Parme89** [comment] 2018-04-16 20:31
i updated to latest ES and now it works fine

**Comment by HumanTree92** [comment] 2018-04-16 21:00
@Parme89 Can you spawn Cones & do they show up?

**Comment by Parme89** [comment] 2018-04-16 21:06
Yes after i updated es to 5.002 and took that manifest and pasted into esx resource.lua

**Comment by HumanTree92** [comment] 2018-04-16 21:37
@Parme89  You when you said that you took that manifest & pasted it into esx_resouce.lua you mean you took the manifest from essentialmode 5.0.2 & put it into esx_policejob in the __resource.lua correct?

**Comment by Parme89** [comment] 2018-04-16 22:07
Yeah i took the es5 manifest and replaced the esx manifest . I didnt change policejob manifest

**Comment by HumanTree92** [comment] 2018-04-16 22:14
Sorry @Parme89 i am still not getting what you mean on replaced the esx manifest. You took ES5 Manifest & put it in what ESX Script. es_extended?

**Comment by HumanTree92** [comment] 2018-04-17 23:56
Thanks @Parme89 still learning about FiveM.

**Comment by HumanTree92** [comment] 2018-05-24 09:13
Is anybody else still having this problem. Like now i can't spawn any props in at all.

**Comment by sirmarknlddr** [comment] 2018-05-24 10:39
Same here, it's being caused by the new resource manifest that Dex++ pushed for ELS+ compatibility. Changing the es_extended resource manifest back to what it was will fix it, but that will break ELS+ compatibility and is not really a viable solution for the future..

**Comment by HumanTree92** [comment] 2018-05-24 16:21
As for ELS your talking about ELS Vehicles? I will try the old one b/c i don't use ELS Vehicles. I only use ELS Style lighting.

**Comment by benzon** [comment] 2018-06-12 03:11
Any chance this will be fixed soon? since it's quite an important feature.

**Comment by Parme89** [comment] 2018-06-12 16:04
You gotta fix it yourself

**Comment by HumanTree92** [comment] 2018-06-13 02:31
Depends on what u use. If you use ELS cars then there isn't much you can do. But if u don't use ELS cars then you can easily fix it yourself. You can simply take the resource manifest from esx_policejob and replace the one in es_extended. Thats how i fixed my issue. But i don't use ELS Vehicles.

**Comment by ElPumpo** [comment] 2018-06-13 05:58
HumanTree your workaround is not specific enough. You can't just switch back the manifest version without reverting the changes

**Comment by HumanTree92** [comment] 2018-06-13 06:31
Well i'm just stating that i have been using my method and haven't had any problems.

**Comment by ElPumpo** [comment] 2018-06-16 08:32
https://github.com/ESX-Org/es_extended/commit/74d27e4d807df57c32ce9145ec659d2c48422258 fixed, update esx

**Closed by ElPumpo** 2018-06-16 08:32 UTC
Labels: bug
